services:
  web:
    build: .
    container_name: ehepa_web

    ports:
      - "80:80"
      - "443:443"

    volumes:
      # Source code
      - ./app:/var/www/html

      # Apache vhosts (SEMUA conf)
      - ./docker/apache:/etc/apache2/sites-enabled

      # GLOBAL ServerName
      - ./docker/apache/servername.conf:/etc/apache2/conf-enabled/servername.conf

      # SSL cert (Windows mkcert)
      - ./docker/ssl:/etc/apache2/ssl

      # Custom PHP config
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini

    environment:
      IS_DOCKER: "1"
