services:
  web:
    build: .
    container_name: ebase_web

    ports:
      - "80:80"
      - "443:443"

    volumes:
      # Source code
      - ./app:/var/www/html

      # Apache vhost (HTTPS)
      - ./docker/apache/ebase.dev.conf:/etc/apache2/sites-enabled/000-default.conf

      # 🔧 GLOBAL ServerName (INI FIX UTAMA)
      - ./docker/apache/servername.conf:/etc/apache2/conf-enabled/servername.conf

      # SSL cert
      - ./docker/ssl:/etc/apache2/ssl

      # Custom PHP config
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini

    environment:
      IS_DOCKER: "1"
